controller_list:
  - name: fake_er7pro_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
  - name: fake_dh_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses per group
  - group: er7pro_arm
    pose: home
  - group: dh_gripper
    pose: open